# Generated by Django 2.2.13 on 2020-12-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=2550, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phone',
                'managed': False,
            },
        ),
    ]
